# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 759)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Import_Page = QtWidgets.QWidget()
        self.Import_Page.setObjectName("Import_Page")
        self.frame = QtWidgets.QFrame(self.Import_Page)
        self.frame.setGeometry(QtCore.QRect(320, 210, 391, 248))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Upload_image_label = QtWidgets.QLabel(self.frame)
        self.Upload_image_label.setLineWidth(0)
        self.Upload_image_label.setObjectName("Upload_image_label")
        self.gridLayout_2.addWidget(self.Upload_image_label, 0, 0, 1, 1)
        self.Upload_label = QtWidgets.QLabel(self.frame)
        self.Upload_label.setStyleSheet("font: 75 16pt \"Consolas\";")
        self.Upload_label.setObjectName("Upload_label")
        self.gridLayout_2.addWidget(self.Upload_label, 1, 0, 1, 1)
        self.Import_button = QtWidgets.QPushButton(self.frame)
        self.Import_button.setMinimumSize(QtCore.QSize(350, 0))
        self.Import_button.setMaximumSize(QtCore.QSize(350, 32))
        self.Import_button.setStyleSheet("font: 75 16pt \"Consolas\";\n"
"")
        self.Import_button.setAutoDefault(False)
        self.Import_button.setDefault(False)
        self.Import_button.setFlat(False)
        self.Import_button.setObjectName("Import_button")
        self.gridLayout_2.addWidget(self.Import_button, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.Import_Page)
        self.Result_Page = QtWidgets.QWidget()
        self.Result_Page.setObjectName("Result_Page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Result_Page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upper_frame = QtWidgets.QFrame(self.Result_Page)
        self.upper_frame.setEnabled(True)
        self.upper_frame.setMinimumSize(QtCore.QSize(1019, 0))
        self.upper_frame.setMaximumSize(QtCore.QSize(1019, 40))
        self.upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upper_frame.setObjectName("upper_frame")
        self.Export_button = QtWidgets.QPushButton(self.upper_frame)
        self.Export_button.setGeometry(QtCore.QRect(830, 10, 75, 23))
        self.Export_button.setObjectName("Export_button")
        self.return_button = QtWidgets.QPushButton(self.upper_frame)
        self.return_button.setGeometry(QtCore.QRect(920, 10, 81, 21))
        self.return_button.setObjectName("return_button")
        self.verticalLayout.addWidget(self.upper_frame)
        self.lower_frame = QtWidgets.QFrame(self.Result_Page)
        self.lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lower_frame.setObjectName("lower_frame")
        self.verticalLayout.addWidget(self.lower_frame)
        self.stackedWidget.addWidget(self.Result_Page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Scoring"))
        self.Upload_image_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/image/src/image/upload.png\"/></p></body></html>"))
        self.Upload_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Drag &amp; Drop image files </span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">or</span></p></body></html>"))
        self.Import_button.setText(_translate("MainWindow", "Import"))
        self.Export_button.setText(_translate("MainWindow", "Export"))
        self.return_button.setText(_translate("MainWindow", "Return"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
import image_rcs_rc
